### ISSUE TITLE
按照步骤安装，但是还是不成功，不知道那里出了问题，可以从那些地方检测呢？

### ISSUE THREAD

**Issue by aceseo** [fuzqing/WeChatShare#1]
- [x] 插件安装及配置；
- [x] 服务器IP地址加入白名单
- [x] 加入JS安全域名
- [x] Typecho的配置
------
疑惑：
主题，目前使用跟作者一样的主题，handsome，不太清楚是否有冲突；
对作者的文章页面进行了微信群分享，跟我配置完成是一致的，都没有正常显示配置的图片和描述。
故在此，求解答

**Comment by aceseo** [comment]
追加问题：
目前WeChatShare插件与Wetypecho（微信小程序）插件一起使用，会导致小程序无法抓取thumb的图片，不知道是否是微信分享的时候对文章链接进行了重写。

**Comment by fuzqing** [comment]
@aceseo 你好，这个插件需要已经**认证**了的微信公众号才可以使用。
插件是帮别人写的，我自己其实并不需要，当时写的时候刚好用他的公众号做测试，测试完成之后我就禁用了。至于版本问题，不限制开发版或者稳定版。
如果你用的微信公众号**已经认证**了，微信端的配置也是正确，还是不能正常使用此插件的话，可以继续留言反馈。

**Comment by aceseo** [comment]
我的就是认证的，不过目前因为做小程序，插件冲突，暂时没有用了。
