### ISSUE TITLE
麻烦大大给看下什么问题

### ISSUE THREAD

**Issue by M3D4** [fuzqing/WeChatShare#2]
使用这个插件，分享给好友没有问题，标题和简介还有图标都正常，但是文章分享朋友圈的话，显示的标题就是后台填写的简介，希望大大给看下什么问题，怎么修复下

**Comment by fuzqing** [comment]
你好，我这边测试了是正常的，请问你确定分享的是同一篇文章吗？
用的什么主题，什么环境
